### ISSUE TITLE
Support Cloudformation Type configuration

### ISSUE THREAD

**Issue by webratz** [opsgenie/opsgenie-cloudformation-resources#13]
Hey,

currently the custom resources requires the `ApiKey` parameter to be set. While this could be filled via a CloudFormation Dynamic reference (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html) it still needs to be specified on every call of the resource.

CloudFormation supports an account Level configuration, which would make it possible that the secret is centrally made available and configured, therefore not each user would have to have access to the secret.

You can find more details on how to do that at
https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-model.html#resource-type-howto-configuration
Which then will be configured on an account level via the following call https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/set-type-configuration.html
This would then look sth like this:

```sh
aws cloudformation set-type-configuration \
    --type-name "Atlassian::Opsgenie::Integration" \
    --type RESOURCE \
    --configuration '{"OpsgenieSettings": {"Endpoint": "api.eu.opsgenie.com", "ApiKey": "{{resolve:secretsmanager:MyOpsgenieSecret:SecretString:APIKey}}"}}'
```

You can see the typeconfiguration for example in Datadogs custom resources at https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-dashboards-dashboard-handler/datadog-dashboards-dashboard.json#L6-L13

**Comment by frknyldz** [comment]
Hi @webratz, thanks a lot for the analysis. The support has been added to the new version `2.0.0`. I'm closing the issue.
