### ISSUE TITLE
S3 URLs in Documentation do not work

### ISSUE THREAD

**Issue by webratz** [opsgenie/opsgenie-cloudformation-resources#14]
When trying to install the integration as described in the readme the command fails.
It seems either the file does not exist, or the permissions on the bucket are wrong.

```sh
aws s3 cp s3://opsgeniedownloads/cloudformation/atlassian-opsgenie-integration-v1.1.zip .                                                                                              
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```
It also fails with a direct API call
```sh
 aws s3api get-object --bucket opsgeniedownloads --key /cloudformation/atlassian-opsgenie-integration-v1.1.zip test.zip                                                             
An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

Can you please update the docs to the latest versions on these bucket and ensure that it can be downloaded?

**Comment by webratz** [comment]
![Screenshot 2022-02-08 at 08 18 23](https://user-images.githubusercontent.com/2162832/152937249-1d798ac7-556d-4096-bb4d-8073eb46f176.png)
Also in the public cloudformation registry only 1.0.0 and 1.0.1 is listed, but the docs say 1.1 is the recent version to be used 🤔

**Comment by webratz** [comment]
Also as an additional note, the command as described in the README is not working either.
```sh
 aws cloudformation register-type \                                                                                                                                      
--region eu-central-1 \
--type-name "Atlassian::Opsgenie::Integration" \
--schema-handler-package "s3://opsgeniedownloads/cloudformation/atlassian-opsgenie-integration-v1.1.zip" \
--type RESOURCE

An error occurred (CFNRegistryException) when calling the RegisterType operation: Error validating schemaHandlerPackage. Check the permissions on the bucket and object in your account and try again.
```

**Comment by frknyldz** [comment]
Hi @webratz , [README.md](https://github.com/opsgenie/opsgenie-cloudformation-resources/blob/master/README.md) has been updated. I've listed installation options.
