### ISSUE TITLE
Atlassian::Opsgenie::Integration

### ISSUE THREAD

**Issue by pgarbe** [opsgenie/opsgenie-cloudformation-resources#15]
Hi,
when using the Atlassian::Opsgenie::Integration resource it creates (and also deletes) the integration in Opsgenie. But, it fails when I want to read either `integrationId` or `integrationApiKey`. 

The error is

```
Unable to retrieve IntegrationApiKey attribute for Atlassian::Opsgenie::Integration, with error message Expected URL scheme 'http' or 'https' but no colon was found
```

How to reproduce:

```json
"Resources": {
  "OpsgenieApiIntegration": {
    "Type": "Atlassian::Opsgenie::Integration",
    "Properties": {
      "OpsgenieApiEndpoint": "https://api.opsgenie.com",
      "OpsgenieApiKey": "{{resolve:secretsmanager...}}",
      "Enabled": true,
      "Name": "MyteamName-API"
      "IntegrationType": "API",
      "OwnerTeamName": "MyteamName"
    }
  }
},
"Outputs": {
  "IntegrationId": {
    "Value": {
      "Fn::GetAtt": [
        "OpsgenieApiIntegration",
        "IntegrationId"
      ]
    }
  }
}
```

**Comment by frknyldz** [comment]
Hi @pgarbe, I've tested with [integration-example](https://github.com/opsgenie/opsgenie-cloudformation-resources/blob/master/examples/opsgenie_integration/stack.json), and it works. I'm able to see `integrationId` output. Could you please try again with the new version? I'm closing the issue for now. Re-open the issue if the problem occurs.
