### ISSUE TITLE
Integration: Attribute 'IntegrationApiKey' does not exist.

### ISSUE THREAD

**Issue by ryanwilliams83** [opsgenie/opsgenie-cloudformation-resources#17]
I'm trying to create an Atlassian::Opsgenie::Integration and retrieve the IntegrationApiKey to use later in an AWS::SNS::Subscription by following the documentation at https://support.atlassian.com/opsgenie/docs/opsgenie-cloudformation-resources/

But CloudFormation is returning error: "Attribute 'IntegrationApiKey' does not exist."

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Opsgenie Integration",
  "Resources": {
    "TestIntegrationTeam": {
      "Type": "Atlassian::Opsgenie::Team",
      "Properties": {
        "Name": "integration-test-team",
        "Description": "Test team to use with integration",
        "Members": []
      }
    },
    "TestIntegration": {
      "Type": "Atlassian::Opsgenie::Integration",
      "Properties": {
        "IntegrationType": "AmazonSns",
        "Name": "test-cfn-integration",
        "Enabled": true,
        "OwnerTeamName" : "integration-test-team",
        "AllowReadAccess": true,
        "AllowWriteAccess": true,
        "AllowDeleteAccess": true,
        "AllowConfigurationAccess": true,
        "Responders": [
          {
            "type": "team",
            "name": "integration-test-team"
          }
        ]
      },
      "DependsOn": [
        "TestIntegrationTeam"
      ]
    }
  },
  "Outputs": {
    "TeamId": {
      "Description": "Opsgenie TeamId",
      "Value": {
        "Fn::GetAtt": [
          "TestIntegrationTeam",
          "TeamId"
        ]
      }
    },
    "IntegrationId": {
      "Description": "Opsgenie IntegrationId",
      "Value": {
        "Fn::GetAtt": [
          "TestIntegration",
          "IntegrationId"
        ]
      }
    },
    "IntegrationApiKey": {
      "Description": "Opsgenie IntegrationApiKey",
      "Value": {
        "Fn::GetAtt": [
          "TestIntegration",
          "IntegrationApiKey"
        ]
      }
    }
  }
}

```

**Comment by frknyldz** [comment]
Hi @ryanwilliams83 , sorry for the late response. We were testing the scenario.
Firstly, thanks a lot for informing us. We did the necessary changes and published new resources(2.0.1) us-west-2 and eu-central-1 regions. If you want to test it in a different region, you need to register it manually. Instructions explained in [README.md](https://github.com/opsgenie/opsgenie-cloudformation-resources/blob/1b30c93ed06160dc348d107c5f9dbea77559b103/README.md)
The example stack templates have changed, and we've verified that apiKey output is available with the new resources.
Tested with the [example](https://github.com/opsgenie/opsgenie-cloudformation-resources/blob/1b30c93ed06160dc348d107c5f9dbea77559b103/examples/e2e/complete.json). I've attached the screenshots.
I hope it fixes your issue. Please, reopen it if you need more help!
<img width="1845" alt="Screen Shot 2022-06-29 at 10 20 35 AM" src="https://user-images.githubusercontent.com/23285358/176438506-8e50266b-473e-4e5e-92aa-974bd692c308.png">
<img width="1919" alt="Screen Shot 2022-06-29 at 10 20 52 AM" src="https://user-images.githubusercontent.com/23285358/176438528-916e294f-78ec-4b48-a876-7100c822ff68.png">
