### ISSUE TITLE
Creation of User fails

### ISSUE THREAD

**Issue by pgarbe** [opsgenie/opsgenie-cloudformation-resources#4]
After having the types successfully installed, I'm running now into an "internal failure" when I try to deploy the e2e example. 

My Cloudformation stack output:

```
2020-02-17 15:12:57 UTC+0100	opsgenie-demo	ROLLBACK_IN_PROGRESS	The following resource(s) failed to create: [UserB, UserA]. . Rollback requested by user.
2020-02-17 15:12:56 UTC+0100	UserA	CREATE_FAILED	Internal Failure
2020-02-17 15:12:56 UTC+0100	UserB	CREATE_FAILED	Internal Failure
```

**Comment by ffahri** [comment]
Hey @pgarbe i tested and its working the user creation 
i also tested e2e json and its working as well. 
You may have same user email in your account created before. 
Logs can be found in cloudwatch logs and you need to add logging config in aws cloudformation register-type cmd
```
--logging-config "{\"LogRoleArn\":\"arn:aws:iam::AWSACCOUNTID:role/cf-log-role\",\"LogGroupName\": \"user-log-group\"}" --type RESOURCE
```

**Comment by pgarbe** [comment]
Thanks for your support @ffahri but I still can't get it to work. Even with the logging config, I don't get any logs. Can you share the definition of your `cf-log-role`?

**Comment by ffahri** [comment]
Attached policies
- CloudWatchLogsFullAccess
Trust Relationships: Cloudformation

should enough. i gave it full access for testing*

**Comment by pgarbe** [comment]
I've the same policies in my role but still don't see any logs. Let's see if the AWS support can help here. But a more descriptive error message (instead of "Internal failure") would be very helpful..

**Comment by pgarbe** [comment]
The reason why no logs have been written is that the role's trust policy has to grant      `resources.cloudformation.amazonaws.com` and not just cloudformation.amazonaws.com.

In the log it says that it's some authentication issue which I'll deal on myself.
